name: Generate Extension Artifacts
run-name: Generate ZIP and CRX
on:
  push:
    branches:
    - main
    - actions-test
jobs:
  generate_zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Archive Release
        uses: TheDoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          directory: 'extension/'
          filename: 'keeptradecut-sleeper-values.zip'
